language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run coverage
  - npm run report-coverage
  - npm run build
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN
    local_dir: build
    on:
      branch: master
  - provider: npm
    skip_cleanup: true
    email: "sanjay1909@gmail.com"
    api_key: $GH_TOKEN
    on:
      tags: true

