language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run coverage
  - npm run report-coverage
  - npm run build
  - npm run doc
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN
    local_dir: build
    on:
      branch: master
  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    on:
      tags: true
      branch: master

